<?php

namespace backend\controllers;

use yii\web\Controller;

/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2017/12/23
 * Time: 16:13
 */
class ColumnsController extends Controller
{
    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->view->params['tag'] = 'contents';
        $this->view->params['tag_li'] = \Yii::$app->controller->id . '/' . \Yii::$app->controller->action->id;
        return true;
    }

    public function actionList()
    {
        return $this->render('list');
    }

    public function actionAdd()
    {
        return $this->render('add');
    }
}