<?php

namespace backend\controllers;

use yii\web\Controller;

/**
 * @author: qunfu
 * @date: 2017/12/26
 * @description:
 */
class ContentsController extends Controller
{
    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->view->params['tag'] = 'contents';
        return true;
    }

    public function actionList()
    {
        return $this->render('list');
    }

    public function actionAdd()
    {
        return $this->render('add');
    }

    public function actionCheckList()
    {
        return $this->render('list');
    }

    public function actionsRecycle()
    {
        $this->view->params['btnTag'] = 'recycle';
        return $this->render('list');
    }
}