<?php
namespace backend\controllers;
use yii\web\Controller;

/**
 * @author: qunfu
 * @date: 2018/1/4
 * @description:
 */
class DataManageController extends Controller
{
    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->view->params['tag'] = 'functions';
        $this->view->params['tag_li'] = \Yii::$app->controller->id . '/' . \Yii::$app->controller->action->id;        return true;
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionAdd()
    {
        return $this->render('add');
    }
}