<?php

namespace backend\controllers;

use yii\web\Controller;

/**
 * @author: qunfu
 * @date: 2017/12/28
 * @description:
 */
class RoleController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->view->params['tag'] = 'users';
        return true;
    }
    public function actionList()
    {
        return $this->render('list');
    }

    public function actionAdd()
    {
        return $this->render('add');
    }

    public function actionPost()
    {
        $request = \Yii::$app->request;
        $post = $request->post();
        return json_encode($post);
    }
}