<?php

namespace backend\controllers;

use yii\web\Controller;

/**
 * @author: qunfu
 * @date: 2018/1/2
 * @description:
 */
class SettingsController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->view->params['tag'] = 'settings';
        return true;
    }
    public function actionIndex()
    {
        return $this->render('index');
    }
}